name: Deploy to Preview
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  FirestoreHostingDeployToPreview:
    name: FirestoreHostingDeployToPreview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"

      - name: npm install
        run: npm i

      - name: install tree and jq
        run: |
          sudo apt update
          sudo apt install -y tree jq

      - name: Install Dependencies
        run: |
          npm install
          npm install -g firebase-tools

      - name: Build
        run: npm run build

      - name: DeployToPreview
        id: deploy-to-preview
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          TOKEN=${{ secrets.FIREBASE_TOKEN }}
          PREVIEW_URL=$(firebase hosting:channel:deploy $PR_NUMBER --token=$TOKEN  --json | jq -r '.result."ratrun-564ac".url')
          echo "::set-output name=preview_url::$PREVIEW_URL"

      # すでにPreviewのURLがコメントされていたらそれを見つける
      - uses: peter-evans/find-comment@v1
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Storybook preview has been deployed!

      # PRがオープンされた最初にだけPreviewのURLをコメントする
      - name: comments to PR
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Preview URL :arrow_right: ${{ steps.deploy-to-preview.outputs.preview_url }}
          edit-mode: replace
